# try-catch-finally
try-catch-finally小实验，java实现
无论是否发生异常，try块中的代码都会执行。
如果try块中发生了异常，并且该异常类型与catch块中指定的异常类型匹配，则catch块中的代码会执行。
无论是否发生异常，finally块中的代码始终会执行。
如果try或catch块中的代码因为异常而被中断，finally块中的代码仍然会执行。
在finally块执行后，控制权会返回到try-catch-finally结构之后的代码。
